### ISSUE TITLE
[help]请各位学员在此提交反馈意见

### ISSUE THREAD

**Issue by cnfeat** [OpenMindClub/OMC.App#1]
各位同学都知道，「芝麻星」是一休带着小伙伴，从10月10号每天不吃不喝不拉不撒，工作「42小时」，搞出来的系统。为了加速各位学员的学习进展，也为了让各位见证一套完整的ai系统如何诞生的，所以现在就投入使用啦！

当然.....

问题非常多！欢迎各位找虫！各位学员使用时碰到的问题，请发在这里：

https://github.com/OpenMindClub/zhimastar

还记得github使用issues的礼仪吗？礼仪练习时间到！

**Comment by aJiea** [comment]
【原因有4】最小思维模式分析解决问题：
左.中.右+意外
上.中.下+意外
内.间.外+异常
快.适.慢+意外
冷.温.热+意外
过去.现在.未来+意外

这张卡没有get到是什么意思？

**Comment by zoejane** [comment]
嘻嘻，有好玩的卡片系统了。  
提到卡片，之前其实听得最多的时记忆卡，这次开发的系统里还有能量卡和行动卡，顿时觉得卡片系统变得更有意思啦。  
希望能像游戏一样好玩 ^_^
你们紧张的开发也辛苦了喔，谢谢你们啦！

刚刚使用使用了“系统卡包”的“卡片系统新手指引”部分，刚刚碰到的一些问题，在这里请教一下：

### 卡片里“进一步阅读”中提供的链接有几个无法打开
具体包括

-  什么是卡片? [纳博科夫的卡片 - 阳志平的网志](http://www.yangzhiping.com/Psy/Nabokov.Html)
-  可以来一个记忆卡示范吗? [Github 故事:欢迎来到开源世界 | 极客公园](http://www.geekpark.net/Topics/201147)
-  可以来一个能量卡示范吗? [专栏 | 肖凯:需要相亲几次才能找到靠谱的对象?](http://devres.zoomquiet.io/Data/20150504205211/Index.Html)

### 卡片背面有评分系统，但评分后好像没有看到具体用途
推测这个功能是还在开发中吧？  
估计卡片系统是根据这个来重新安排复习计划的。

### 已经学过、正在学习的，没学过的卡片可以进行区分吗？可以自动保留进度吗？
卡片较多，可能有时候都不知道自己学到哪里了。  
除了添加到收藏之外，可以标注出自己还没学过或正在学习的卡片吗？  
可以自动保留某个卡包组里，自己学习到的进度吗？

### 暂时没找到如何自己添加卡片
在“我的卡包”里，可以放一些自己的卡片，但是刚刚翻了一圈，暂时还没有找到添加卡片的入口

### 卡片的颜色有特别的意义吗
看到卡片有红黄蓝绿四种颜色，不知道这个颜色有特别的意义吗？  
之前猜测是按记忆、行动、能量的种类或者是自己的记忆难度划分的，但是刚刚试验了一下，好像不是的。

**Comment by penguinjing** [comment]
第一次尝试用Github关联登陆，网页返回：
> {"result":{"code":"10021","message":"无法获取您的 github 邮箱,请更新您 github 账户设置中 Public email 选项!"}}

进入个人Github页面，点击：右上角个人头像 -> Setting -> Public Profile里
把Public email 选项从不显示我的邮箱-> 更改为显示邮箱ok，芝麻星登陆正常。

尝试将Public email选项更改为非github用的注册邮箱，也可正常登陆。
看来是"没法获得我的公开邮箱信息，请更新您Github账户设置中Public email选项."

**Comment by ouyangzhiping** [comment]
@zoejane 非常精彩的意见。

>1. 卡片里“进一步阅读”中提供的链接有几个无法打开

此功能正在完善中，下周会搞定。

>2.卡片背面有评分系统，但评分后好像没有看到具体用途

你的猜测是对的。

>3.已经学过、正在学习的，没学过的卡片可以进行区分吗？可以自动保留进度吗？

好建议！已经学过、正在学习的，没学过的卡片会进行区分的；自动保留进度也会加上的！

>4. 暂时没找到如何自己添加卡片

入口是未来版本开发重心。

>5. 卡片的颜色有特别的意义吗

有非常特殊的意义。大家以后会慢慢看到:D

再次感谢你非常精彩的意见！

**Comment by linttutu** [comment]
进入芝麻星系统后，进入卡片，点击“查看卡片”时，出现404，

**Comment by ouyangzhiping** [comment]
@linttutu 具体哪张卡片？对应哪个卡包？还是所有卡片均如此？

**Comment by linttutu** [comment]
并没有每张都点。我尝试的是0w内的几张，打开后可以看到内容，点击上方查看卡片就出现 404，
不清楚芝麻星卡片系统除了登陆以外，有没有其他要求。
今天没尝试。

发自我的 Windows Phone
________________________________
发件人: Zhiping Yang<mailto:notifications@github.com>
发送时间: ‎2015/‎10/‎18 8:50
收件人: OpenMindClub/zhimastar<mailto:zhimastar@noreply.github.com>
抄送: lingtutu<mailto:lingtutuya@outlook.com>
主题: Re: [zhimastar] [help]请各位学员在此提交反馈意见 (#1)

@linttutu 具体哪张卡片？对应哪个卡包？还是所有卡片均如此？

---

**Comment by zoejane** [comment]
从10月17日晚上到10月18日上午使用期间，经常会出现

An error occurred.
> Sorry, the page you are looking for is currently unavailable.
> Please try again later.
> If you are the system administrator of this resource then you should check
> theerror log for details.
> Faithfully yours, nginx.


在服务器不够稳定的情况下，可否考虑将每周的任务卡片还是放在github的issue里方便查阅？
个人现在准备看到任务卡片先放到evernote里备用。
因为一些学习资源还可以想办法去google，但是任务的查看好像只能在芝麻星里。

**Comment by hysic** [comment]
无法从“查看卡片”页面通过“后退”键返回“卡片列表”页面。

从“任务列表”进入“卡片列表”进入“查看卡片”，我想返回“卡片列表”，点击浏览器的“后退”，地址栏的URL发生了变化，但页面显示并未发生变化，再点一下“后退”，页面就回到“任务列表”。如果我想从“查看卡片”页面返回“卡片列表”页面，只能点击右上角的“x”。

OS X 10.10 + Chrome 41

**Comment by ishanshan** [comment]
过期关闭
