### ISSUE TITLE
安卓版 新手村卡包点击无反应且无法上下滑动

### ISSUE THREAD

**Issue by chousawa** [OpenMindClub/OMC.App#10]
点击主页的“创作”跳到卡包标签后，页面就卡住了，点击“新手村”，无反应，也无法上下滑动。点击其他标签之后再点卡包，出现的是黑屏，如下：
![](http://ww2.sinaimg.cn/large/94dd4cd4gw1f1u6f2ga2dj20u01hc40l.jpg)

再点击主页的“创作”跳到卡包标签，页面是白屏，如下：

![](http://ww4.sinaimg.cn/large/94dd4cd4gw1f1u6fnnuyij20u01hc75n.jpg)

**Comment by newjueqi** [comment]
我的手机是华为荣耀4x，android系统是4.4.2，也遇到同样的问题

**Comment by ouyangzhiping** [comment]
感谢 @chousawa  @newjueqi 的反馈！

**Comment by spring-Lyn** [comment]
红米手机，安卓系统，同样有这个问题

**Comment by ShuangFarmer** [comment]
小米手机2s，安卓系统，系统升级前遇到相同问题，系统升级到最新版本，能够正常使用开智学堂app。

**Comment by ImCaos** [comment]
多谢大家的反馈，安卓低版本兼容问题正在解决中~

**Comment by badboy315** [comment]
目前建议可以使用网页端(手机 和 PC 都可以打开网页端学习)

http://www.openmindclub.com/ 进行学习

**Comment by mix-xu** [comment]
症状：WEB，APP页面里面都无法上下滚动
WEB：win7系统，chrome浏览器
app：魅族手机，安卓系统4.4.4

**Comment by badboy315** [comment]
@mix-xu 

1. 安卓部分机型存在 bug. 工程师正在修复, 建议使用网页版本 http://www.openmindclub.com/ 或 ios 版.
2. 网页版本请 用鼠标中间的 轮滑 再试下.

**Comment by lilingxinyi** [comment]
网页版，用鼠标中间的轮滑，也不能上下滑动，只能显示新手村中的前4页。

**Comment by badboy315** [comment]
已归类 https://github.com/OpenMindClub/OMC.App/issues/21 处理, 关闭此 Issue
