### ISSUE TITLE
IOS版：开智学堂bug反馈

### ISSUE THREAD

**Issue by MissUUU** [OpenMindClub/OMC.App#11]
环境：IOS/iphone6

【卡包功能】：每张卡片可重复多次评分
【卡包功能】：评分后，提示框”评分成功“消失过快，无需点击OK键
【卡包功能】：点击某一卡片后，当前界面会刷新闪烁下，才进入卡片内容（点击返回键，界面也会刷新闪烁）
【卡包功能】：新手村的倒数第三张卡片【可以来一张测试卡示范吗？】checkbox很难选中，且点击checkbox控件会闪烁。
【卡包功能】：查看排行榜，点击GitHub、小作业、大作业页签，控件会闪烁变黑
【功能页签】：切换点击主页、卡包、视频、我页签时，控件会闪烁变黑

**Comment by ouyangzhiping** [comment]
感谢 @MissUUU 很棒的反馈！

**Comment by badboy315** [comment]
感谢 专业 和 细致 的反馈建议， 已经列入 开发需求清单。
