### ISSUE TITLE
样式改进建议

### ISSUE THREAD

**Issue by ishanshan** [OpenMindClub/OMC.App#12]
以下建议来自  @fffman 

环境：IOS / iPhone Plus

- [ ] 1. 卡片翻转。翻转按键的图形太像『刷新键』，容易误导，建议更改。翻转按键的位置处于右上角，与各类app中功能键或转发键的位置接近，用户容易习惯性误解，或者忽视。即便熟悉了，按起来也不方便。建议改为划屏翻页，更符合用户习惯。或者将翻转按钮与收藏按钮兑换，用户看完后默认点击即可翻页，翻页看完可以评分，或分享（收藏）到自己的库或外部平台（引流）。
- [ ]  2. 卡片字体。文字太小，看起来很累，建议调大，或者提供字体调整选项。
- [ ] 3. 卡片颜色。颜色给人第一感觉是小女生的日记软件，建议找更大气的设计方案。此外，可以考虑横版卡片设计，更符合传统风格。
- [ ] 4. 卡片内容。能量卡现在是文字，建议改为图片，更符合人脑口味。可以考虑直接引入优质图片，或由其他用户贡献（分享后被点赞可获得积分奖励，强化游戏化思维）。
- [ ] 5. 卡片名称。现在的卡片名称记忆起来有点辛苦，在文字堆里不明显，建议都给予英文命名和缩写，FlashCard就是FC，EnergyCard就是EC，etc.

**Comment by mumu1314** [comment]
1.卡片内容是图片的基本看不清内容，太小，而且不能点击放大
2.卡片不能单击翻转，不同卡片切换也不能滑动操作，很不方便

**Comment by badboy315** [comment]
建议已纳入开发需求清单, 关闭此 GitHub Issue
