### ISSUE TITLE
建议开通手机端反馈 Bug 渠道

### ISSUE THREAD

**Issue by ishanshan** [OpenMindClub/OMC.App#13]
建议来自 @fffman ：目前 BUG 反馈渠道单一，建议开通手机端的直接用户反馈，减少用户切换设备的时间（成本），从而让更多人的碎片时间能用于试错和报错。

**Comment by ImCaos** [comment]
收到

**Comment by badboy315** [comment]
列入 需求清单， 关闭 issue
