### ISSUE TITLE
网页版进入后卡包无法打开

### ISSUE THREAD

**Issue by gunuo** [OpenMindClub/OMC.App#14]
显示元技能进行中，但点上去没有反应。

**Comment by badboy315** [comment]
现在是否还存在此问题?

如还存在, 回复一下 手机型号和版本

**Comment by mumu1314** [comment]
同存在此问题，是电脑，Windows 7 家庭普通版，试过IE，chrome，都打不开卡包，鼠标悬停还是指针，没有变化，但是未解锁的卡包可以点击，会提示“未解锁”

**Comment by badboy315** [comment]
@mumu1314 悬停指针不影响点击打开。 部分 win 系统存在 浏览器插件 问题， 建议安装 adobeflash 插件, 增加 firefox 也可以一试。

@gunuo 已经更新， 请重试。
