### ISSUE TITLE
安卓华为荣耀6无法使用卡包

### ISSUE THREAD

**Issue by Hawli777** [OpenMindClub/OMC.App#15]
卡片系统反馈bugs：
环境：安卓华为荣耀6/web
1.我的web和安卓手机app点击卡包页签后出现“新手村”卡片，但是点击后没有进一步反应，无法进行卡片使用，是否为账号问题，求解决。
2.app中，点击“我”页签后出现我的卡片界面但是拖动界面无效，显示为视频卡、记忆卡、能量卡、行动卡，无法看到下面两种卡类型。
3.app中，卡包页面点击查看排行榜后没有返回卡包选项。

**Comment by ImCaos** [comment]
能提供下安卓系统版本号吗？

**Comment by Hawli777** [comment]
系统版本号：EMUI系统3.0  H60-L02V100R001CHNC00B317
安卓4.4.2

**Comment by badboy315** [comment]
安卓机型问题[huawei]工程师正在处理中
