### ISSUE TITLE
开智学堂各个平台之间的同步

### ISSUE THREAD

**Issue by Chloeinjoy** [OpenMindClub/OMC.App#16]
我发现各个平台之间不能够同步。

我手机，pad，和电脑都用，但是一旦换了平台，就需要从头开始解锁卡片，比如说我用电脑看完了所有卡片，用手机继续学习卡片的时候发现手机平台还停留在上次阅读的第一张卡片。

希望能解决各个终端的同步问题。

谢谢

**Comment by badboy315** [comment]
@Chloeinjoy 

测试: 安卓终端 + PC 终端 是 保持一致的.

如还存在这个问题, 请当时直接 @一休.

**Comment by ouyangzhiping** [comment]
@badboy315  可能是 pad 与 pc或者手机不能保持同步，我今晚似乎也碰到类似现象。
