### ISSUE TITLE
IOS版测试后反馈

### ISSUE THREAD

**Issue by douzhipin** [OpenMindClub/OMC.App#17]
手机型号：IOS/IPHONE5S
网络：移动4G
已解锁内容：新手村、元技能、启程

#### 流程繁琐

- 例如新手村内有14道进程，每道进程都是独立存在的，需要一个个点开、退出、再点开，缺乏连续性。
- 作业排行榜内，看完某学员的大作业后，退出的界面回到“github”，而不是“大作业”界面。

#### 游戏化
- 每次解锁完毕不给点奖励嘛...光靠文字有点缺乏激情呀。
- 每张卡片旁边都有个电池的标识，是说在充电吗？那是不是可以有个总的，当看完全部进度就说明电充满了。

#### 功能
- 测试卡选项间歇性失灵，我开始选了2-6，再点7的时候没有反应，我以为是系统有限定数量，提交后答案错了，再点发现都可以全选的。（点开其他卡片界面也有这样的问题）
- 图片不能放大。图片太小，无法看清楚内容。
- 卡片下面有显示哪些同学看过卡片，但是很多人都没有编辑头像，点进去一片初始头像也没有名字，貌似没啥实际用处。
- 最后强烈建议视频有缓存功能，这样就可以随时看课程的内容了。

**Comment by badboy315** [comment]
@douzhipin 

建议都太棒了, 从用户体验 到 用户激励 再到 用户功能 都有提到,,, 

行家 Geek 范.
