### ISSUE TITLE
"什么是 Github "那张卡片视频不全

### ISSUE THREAD

**Issue by cici1989** [OpenMindClub/OMC.App#18]
"提交作业的三种方式"没有讲完视频就结束了。（在 iPad 上使用 APP，以及用网页版观看都是这种情况）

**Comment by badboy315** [comment]
收到您的反馈, 确实存在这个问题, 稍后让技术人员重新上传.

**Comment by layla1412** [comment]
前三个卡包都显示已经完成了，不知道为啥第四个卡包提示：卡包未解锁请先解锁之前的卡包。

**Comment by badboy315** [comment]
@layla1412 

请参考 https://github.com/OpenMindClub/OMC.App/issues/20

完整一下信息, 新建一条 issue.

**Comment by badboy315** [comment]
已汇总到 https://github.com/OpenMindClub/OMC.App/issues/23#issuecomment-196228395 跟进处理中
