### ISSUE TITLE
技术类 问题汇总

### ISSUE THREAD

**Issue by badboy315** [OpenMindClub/OMC.App#21]
~ 此类收集问题为处理第一序列

> 正常功能无法使用`举例:无法打开\打开为空 等`

- [https://github.com/OpenMindClub/OMC.App/issues/10] #问题:  安卓手机进入卡包空白 #状态: 处理中 #建议:  升级安卓最新版本/PC 端 http://www.openmindclub.com 或 IOS 版本
- [https://github.com/OpenMindClub/OMC.App/issues/22] #问题: 完成无法解锁下个卡包 #状态: 处理中 #建议:  操作指引 https://github.com/OpenMindClub/Writer002/issues/38
    + 同问题[#31]
- [https://github.com/OpenMindClub/OMC.App/issues/30] #问题: 学员头像错落 #状态: 处理中 #建议: 等待版本修复更新

**Comment by badboy315** [comment]
1. [Android]主页进入卡包时黑屏
2. 内容格式：
    - **系统版本**： Android 安卓4.4.2 EMUI系统3.0 H60-L02V100R001CHNC00B317
    - **机型**： 安卓华为荣耀6
    - **使用环境**：安卓 APP \ 手机登录 WEB
    - **触发情景详细描述**：
	    - 进入我的卡包为空
![](https://camo.githubusercontent.com/108b101e8d654d4a677935b56170f6e385b9f3b2/687474703a2f2f7777322e73696e61696d672e636e2f6c617267652f3934646434636434677731663175366632676132646a3230753031686334306c2e6a7067)

3. 测试:

华为机型/部分 安卓机型存在此问题;

4. 状态:

工程师正在处理解决中;

5. 建议:

目前建议使用 PC 端 http://www.openmindclub.com 或 IOS 版本.

**Comment by badboy315** [comment]
[[Android和网页]第四个卡包无法解锁](https://github.com/OpenMindClub/OMC.App/issues/22)

经测试, 已交由工程师紧急修复

**Comment by badboy315** [comment]
os6。
卡片：来吧，不服跑个分。
现象：学员头像错落。
![](http://7xoxk3.com1.z0.glb.clouddn.com/23.pic.jpg)

**Comment by huyang0908** [comment]
## 标题：IOS进入第2个卡包时无法点开第7张卡片
系统版本：IOS9.2.1 型号：Iphone6
触发场景：按顺序打开卡片并进入下一张时卡在第2卡包（元技能）中的《开智元范：用绝对坐标沟通》，无论是手机App端还是Mac Chrome的网页端都无法点开此张卡片。
<img width="391" alt="2016-03-15 12 38 28" src="https://cloud.githubusercontent.com/assets/16854060/13751770/ac96e88e-ea46-11e5-8e7d-55ed8ac274c8.png">

**Comment by ouyangzhiping** [comment]
@huyang0908 收到bug！在工程师解决之前，或许可以试试看 **重启app** ？

**Comment by Git-shawnhu** [comment]
标题格式：[iOS + Mac]+卡包前两个完成了，第三个无法出现

系统版本：[IOS 9.2.1 + OS X EI Capitan]
机型：iPhone 6
使用环境：Safari 、Chrome 48.0.2564.116 (64-bit)
触发情景详细描述：

卡包完成前两个包之后，无法自动出现第三个卡包，无法继续。手机和电脑都如此。
![img_2276](https://cloud.githubusercontent.com/assets/17614932/13766890/c8e77bde-eaa0-11e5-88d0-39eb55d932ef.PNG)

**Comment by xiaoxiong0032** [comment]
1.标题格式：[Android/iOS]+网页进入卡包无显示
2.内容格式： 
◦系统版本：Android 
◦机型：小米2
◦使用环境：WEB登入
◦触发情景详细描述：通过网页登入，点击卡包，无显示

**Comment by badboy315** [comment]
@Git-shawnhu https://github.com/OpenMindClub/Writer002/issues/38 已有指引, 请操作后重试.

**Comment by badboy315** [comment]
@xiaoxiong0032 
https://github.com/OpenMindClub/OMC.App/issues/21#issuecomment-196214220 安卓手机部分存在此问题, 工程师正在处理中.

建议:
1. 建议升级到最新版本.
2. 还是无法运行, 建议用先 PC 网页版 / ios 版.

**Comment by badboy315** [comment]
@huyang0908 https://github.com/OpenMindClub/Writer002/issues/38 已有指引, 请操作后重试.

**Comment by badboy315** [comment]
本 issue 不再接受盖楼, 如有 bug 问题请新建 issue 

提交 bug 前, 请先阅读指南 #20 

在 Issues 中提交 开智学堂 APP 的反馈，请遵循如下格式，这样工程师才好尽快排查处理哦：

1. 标题格式：[Android/iOS]+问题简述，例如：[Android]主页进入卡包时黑屏
2. 内容格式：
    - **系统版本**：例如 Android 5.1.1、OS X EI Capitan Version 10.11.2
    - **机型**：例如 华为 P7 ，电脑可不写该项
    - **使用环境**：例如 QQ 浏览器	、Chrome Version 49.0.2623.75 (64-bit) 
    - **触发情景详细描述**：
	    - 经过了步骤1，步骤2，步骤3……之后，出现了问题
	    - 截图：插入问题关键截图
3. 每个问题发一条 Issue ，而非多个问题汇总在一个 Issue 中
4. 为 Issue 加标签（Labels，在页面右侧边栏可找到）
	- 若为技术问题，加 `bug` 标签
	- 若为改进建议，加 `enhancement` 标签
	- 若为内容错误，加`solecism` 标签
