### ISSUE TITLE
[Android和网页]第四个卡包无法解锁

### ISSUE THREAD

**Issue by layla1412** [OpenMindClub/OMC.App#22]
使用环境：qq浏览器、小米手机安卓系统 4.4.4KTU84p
触发情景描述：卡包前三个都显示已完成，第四个无法解锁。
请问是我操作上有问题吗？
![qq 20160314165909](https://cloud.githubusercontent.com/assets/17695078/13739668/7dad9e62-ea07-11e5-9f2d-73852b5c08c9.png)

**Comment by badboy315** [comment]
[Android和网页]第四个卡包无法解锁

已经汇总到 [技术问题汇总](https://github.com/OpenMindClub/OMC.App/issues/21)

经测试, 已交 工程师 处理中.

**Comment by badboy315** [comment]
已经修复 Bug. 请重新进入查看 @layla1412
