### ISSUE TITLE
内容类 问题汇总

### ISSUE THREAD

**Issue by badboy315** [OpenMindClub/OMC.App#23]
~ 收集关于 文本错误 视频内容 等存在问题汇总

> [必读：Bug 提交方式说明](https://github.com/OpenMindClub/OMC.App/issues/20)

**Comment by badboy315** [comment]
问题：["什么是 Github "视频内容不全](https://github.com/OpenMindClub/OMC.App/issues/18)

状态：已跟进

**Comment by badboy315** [comment]
https://github.com/OpenMindClub/OMC.App/issues/14#issuecomment-196132687

Win / Mac 系统推荐 浏览器 配置/插件

- chrome/firefox  安装 Adobe Flash Player

**Comment by fffman** [comment]
IOS / iPhone 6 Plus

- 160314『开学典礼』章节的《阳老师谈无用的写作》和《阳老师答疑》视频内容一样。请更正。

**Comment by ouyangzhiping** [comment]
@fffman 已修正此bug。

**Comment by cnfeat** [comment]
[23#issuecomment](https://github.com/OpenMindClub/OMC.App/issues/23#issuecomment-196318205)

已解决

**Comment by aJiea** [comment]
- [ ] 【写作课】【领取装备】【4/11】背面 “写匠网址”缺失

**Comment by chousawa** [comment]
web版

- 【启程】【7/7】视频卡“课程结束，我的结业大作业是什么”的视频内容是“马村的夏天”的广告

**Comment by badboy315** [comment]
https://github.com/OpenMindClub/OMC.App/issues/28#issue-141135339

@Azeril #视频音量过小#措施:新视频上传后, 增加 音频 音量.

**Comment by badboy315** [comment]
@aJiea #【写作课】【领取装备】【4/11】背面 “写匠网址”缺失 # 有网址的, 建议刷新一下. 写匠网址提供 http://aiwriter.cn/, 还没有内测, 所以暂时不能使用.

**Comment by badboy315** [comment]
@chousawa 马村的夏天 是一期学员的结业大作业.

**Comment by lulukee** [comment]
【写作之难】【恭喜你，来领取礼包吧】卡片背面是空白的。

**Comment by xiaoronglv** [comment]
这个不可点击的按钮最好能够去掉。


<img width="618" alt="2016-03-16 at 12 59" src="https://cloud.githubusercontent.com/assets/1224077/13802446/faf2c580-eb76-11e5-8473-7b3336d10237.png">

http://openmindclub.com/#/frame/card_video_new/99c789f0-8161-11e5-a837-0800200c9a66//c56abd70-e93a-11e5-84cb-d3ef3e515a76

**Comment by douzhipin** [comment]
【写作之难】里：“还记得写作三难吗？”，选择：1逻辑、3文采、5故事， 提交后提示答案错误。但翻到卡片背面显示的答案就是这三个。

**Comment by badboy315** [comment]
@lulukee 收到反馈， 感谢勘误， 处理中。
@douzhipin 收到反馈， 感谢勘误， 处理中。
@xiaoronglv 收到反馈，感谢建议。

**Comment by kt1130** [comment]
心灵种种一课中，阳老授课视频的16分24秒出现的心智塔模型图片右侧的系统1——系统2似乎写反了，按照阳老的授课内容，应该是诞生于进化早期的心智属于系统1，诞生于晚期的心智属于系统2，所以应该是系统1在下面，系统2在上面。

**Comment by badboy315** [comment]
本 issue 不再接受盖楼, 如有 bug 问题请新建 issue 

提交 bug 前, 请先阅读指南 #20 

在 Issues 中提交 开智学堂 APP 的反馈，请遵循如下格式，这样工程师才好尽快排查处理哦：

1. 标题格式：[Android/iOS]+问题简述，例如：[Android]主页进入卡包时黑屏
2. 内容格式：
    - **系统版本**：例如 Android 5.1.1、OS X EI Capitan Version 10.11.2
    - **机型**：例如 华为 P7 ，电脑可不写该项
    - **使用环境**：例如 QQ 浏览器	、Chrome Version 49.0.2623.75 (64-bit) 
    - **触发情景详细描述**：
	    - 经过了步骤1，步骤2，步骤3……之后，出现了问题
	    - 截图：插入问题关键截图
3. 每个问题发一条 Issue ，而非多个问题汇总在一个 Issue 中
4. 为 Issue 加标签（Labels，在页面右侧边栏可找到）
	- 若为技术问题，加 `bug` 标签
	- 若为改进建议，加 `enhancement` 标签
	- 若为内容错误，加`solecism` 标签
