### ISSUE TITLE
优化类 问题汇总

### ISSUE THREAD

**Issue by badboy315** [OpenMindClub/OMC.App#24]
~ 用于收集产品 使用体验、流程 、设计等优化需求

[必读：Bug 提交方式说明](https://github.com/OpenMindClub/OMC.App/issues/20)

**Comment by badboy315** [comment]
查看大作业后无法返回到大作业栏 https://github.com/OpenMindClub/OMC.App/issues/19

设计建议：同类大作业/小作业 采用同类逐条查看方式

**Comment by badboy315** [comment]
环境：IOS/iphone6 https://github.com/OpenMindClub/OMC.App/issues/11#issue-140382874

【卡包功能】：每张卡片可重复多次评分
【卡包功能】：评分后，提示框”评分成功“消失过快，无需点击OK键
【卡包功能】：点击某一卡片后，当前界面会刷新闪烁下，才进入卡片内容（点击返回键，界面也会刷新闪烁）
【卡包功能】：新手村的倒数第三张卡片【可以来一张测试卡示范吗？】checkbox很难选中，且点击checkbox控件会闪烁。

优化建议: 

1. 卡片评分 多次 需调整;
2. 评分后, OK 键消失;
3. 系统 流畅度, 每次点击的 闪烁;
4. 新手村的倒数第三张卡片【可以来一张测试卡示范吗？】
- 难选, 勾选框变大;
- 多选都是对的, 提示错误

**Comment by fffman** [comment]
环境：IOS / iPhone Plus

- 卡片翻转。翻转按键的图形太像『刷新键』，容易误导，建议更改。翻转按键的位置处于右上角，与各类app中功能键或转发键的位置接近，用户容易习惯性误解，或者忽视。即便熟悉了，按起来也不方便。建议改为划屏翻页，更符合用户习惯。或者将翻转按钮与收藏按钮兑换，用户看完后默认点击即可翻页，翻页看完可以评分，或分享（收藏）到自己的库或外部平台（引流）。
- 卡片字体。文字太小，看起来很累，建议调大，或者提供字体调整选项。
- 卡片颜色。颜色给人第一感觉是小女生的日记软件，建议找更大气的设计方案。此外，可以考虑横版卡片设计，更符合传统风格。
- 卡片内容。能量卡现在是文字，建议改为图片，更符合人脑口味。可以考虑直接引入优质图片，或由其他用户贡献（分享后被点赞可获得积分奖励，强化游戏化思维）。
- 卡片名称。现在的卡片名称记忆起来有点辛苦，在文字堆里不明显，建议都给予英文命名和缩写，FlashCard就是FC，EnergyCard就是EC，etc.
- BUG反馈渠道单一，建议开通手机端的直接用户反馈，减少用户切换设备的时间（成本），从而让更多人的碎片时间能用于试错和报错。

**Comment by badboy315** [comment]
https://github.com/OpenMindClub/OMC.App/issues/17#issue-140570133

优化建议:
1. 自定义头像;
2. 视频缓存;
3. 多选敏捷度;
4. 解锁奖励游戏性设计元素;

**Comment by nanxiaonie** [comment]
[Android]卡包视频不能最大化
  
        系统版本：Android 5.1
        机型：魅族 MX4
        使用环境：APP
        触发情景详细描述：
        步骤1：打开APP;步骤2:选择卡包；步骤3：选择“启程”；步骤4：进度7“课程结束，我的结业大作业是什么？”  上期学员制作的视频字幕太小，看不清，建议视频可以在手机观看时最大化。

**Comment by badboy315** [comment]
@nanxiaonie 

1. 手机设置为 自动旋转屏幕;
2. 单击 视频 右下角出现 全屏的标志, 点击之后横屏观看.

**Comment by badboy315** [comment]
#体验#ios 安卓#卡片和卡片之间能够直接滑动，不用跳转到文件夹再点击进去
https://github.com/OpenMindClub/Writer002/issues/6#issuecomment-196708653

**Comment by aJiea** [comment]
- 魅蓝2
- [ ] 卡片里内置图片太小不可放大，横屏可放大，但是显示不完，点击图片，上下导航不隐藏起来。

**Comment by ShuangFarmer** [comment]
- 评估卡
 1. web端／小米2s: 评估卡背面的信息无法收藏。 
 2. 仅web端：已经提交检查过一次的作业，无法保存。将卡片翻回正面，或者返回卡包后，重新点进这张卡片，需要再次在卡片正面提交检查作业内容才能够翻看卡片背面的内容。

- 卡片搜索
能否开发搜索功能，根据关键词，搜索全部卡包，找到相关卡片？

**Comment by badboy315** [comment]
@aJiea @ShuangFarmer 建议太棒, 第一版发布, 确实存在很多不足. 非常感谢.

#问题:【视频马拉松】无播放进度条，不能进行选择性或重复性观看 #建议:点击视频右下角有全屏功能方大可选进度条.

* 卡片体验改进建议
	1. 卡片图片体验;
	2. 卡片备注功能;
	3. 卡片切换;
	4. 卡片检索;
	5. 卡片内容保存;

**Comment by ivanlau** [comment]
评估卡的评分页面，是否可以给出一些参考信息，例如总分按多少算的，是越高越好还是越低越好等。

**Comment by kt1130** [comment]
问题描述：小作业排行榜的次数是按学员提交作业次数统计的，即使是同一个作业，学员因为修改而重复提交也算一次，故按照该排行榜确定学员学习程度并不准确，如果一个学员因为bug反复提交，那么他很快就能上升到排行榜首位。。。。。

**Comment by badboy315** [comment]
@ivanlau 感谢反馈， 收到建议
@kt1130 感谢反馈， 收到建议

#建议：细分评分计算方式；
#建议：小作业排行榜的合理性；

**Comment by ivanlau** [comment]
希望加上ipad mini适配，貌似字有点小

**Comment by badboy315** [comment]
@ivanlau 收到反馈，收到建议

**Comment by ShuangFarmer** [comment]
评估卡  
- web/小米2s  
- 问题  
提交小作业 -> 点击检查 -> 翻到背面，仅显示自己写的作业，和一些评论或范文。  
如果想要查看写匠ai的修改，需要：离开卡片 -> 返回卡包 -> 进入排行榜 -> 点击小作业 -> 翻找个人账户 -> 查看，这个路径有点曲折。能否提交完小作业后，可以直达写匠ai给的写作反馈呢？

**Comment by badboy315** [comment]
@ShuangFarmer 收到建议，感谢反馈

**Comment by Chloeinjoy** [comment]
环境：IOS/iphone6

@badboy315 

手机端口只显示home页，完全没有办法点击进去其他任何界面（如个人信息页面，或者是课程页面）；
于是我卸载了重新安装了，但是这次停留在输入用户名和密码的界面，完全没有办法点击输入任何东西。

希望能够得到解决^^ 
谢谢！！ #

**Comment by eduream** [comment]
[Android]卡片视频
优化建议：增加视频缓存功能

**Comment by badboy315** [comment]
@Chloeinjoy 技术类问题是新建 issue.
OK. 已交由工程师处理中.

@eduream  收到建议，感谢反馈

**Comment by yqhdzg** [comment]
[红米note2]
收藏卡片按类型分类之外，是否可以增加按周期分类，即第一周、第二周、第三周
有时候查找某个知识点又忘记卡片类型，不是很方便

**Comment by yqhdzg** [comment]
[红米note2]
卡片内容不可复制，希望可以得到优化

**Comment by ivanlau** [comment]
不知是否可以把课程的主视频独立出来，有时候手头忙想直接先听课，但是遇到卡包还没刷到视频而没法直接找到该卡片的情况

**Comment by ouyangzhiping** [comment]
@ivanlau  已经独立出来了。可以先刷完所有卡片，然后点击「视频」，就可以看到你刷过的视频。

**Comment by badboy315** [comment]
@yqhdzg 收到建议，感谢反馈。

**Comment by fffman** [comment]
视频录制的时候，开始和结尾不要让音乐和讲课声音重叠，这样造成不清晰。建议是先音乐起，音乐结束后再开始讲。结果是先讲完，再音乐起。

**Comment by lulukee** [comment]
建议web的开智学堂，卡包界面，用鼠标滚轮速度能快一点，学到后面的卡包要滚半天。谢谢！

**Comment by lulukee** [comment]
一个卡包关闭，就会回到第一个卡包的位置，然后就要往后翻啊翻，有没有办法仍然在关闭的卡包那个位置？

**Comment by badboy315** [comment]
@lulukee 兼容性问题已经收到, 工程师正在处理中.

目前有 部分浏览器 firefox 会有 上下 鼠标滑动慢情况.

建议使用 Chrome

**Comment by badboy315** [comment]
@fffman 感谢反馈, 收到建议

**Comment by fffman** [comment]
1、提醒消息的问题。IOS 9.3下，最新版开智app推送了周六晚上阳老师答疑的信息，但是查看后app右上角的红色消息提示无法消除。
2、卡片系统的问题。由于是根据课程排序的，所以越往后面，用户体验越差，因为要下拉很多才能找到当前的课程，能否改过来，已经听过的课程在下面，最新的课程在上面。
3、离线视频的问题。之前提出来过，感觉还是很迫切的，眼下绝大多数讲课类app都是允许离线的，这个对像我这样移动听课的人来说特别重要，希望能早日实现。

**Comment by cp4** [comment]
### 消极体验
1. 必须打开当前卡片，才能看到后面的卡片，这种方式迫使大家按照顺序学习。
    这对于落后同学非常不利，因为课程信息量大，一旦落后，很可能总也追赶不上，不能和别人一同完成当周作业和笔记，失去得到点评和关注的机会。而且心理负担过重，更容易放弃。
2. 如很多同学反映过的，所有卡片都在一个页面，越来越难查找。
3. 一个卡包里，有些卡片只是用来过渡/说明等，占据卡片的地位增加了认知负担，重点不突出。

### 建议
1. 把每周课程卡包归到同一入口（目录），每周内的卡包只能按顺序打开，但各周的卡包之间不受打开先后的约束。这样，落后的同学可以暂时把落下的课程跳过，轻装上阵开始新课程，也利于分散学习策略；同时，便于查找卡片。
2. 不具备卡片资格的文字，最好以更轻便的方式呈现。
3. 在卡片上显示被收藏数，作为重要性参考。

**Comment by ivanlau** [comment]
ios期待加入横向适配，现在刷卡片横向没反应。使用ipad的时候经常要用到横向，因为支架都是横向才能立起来的，感谢

**Comment by yichunyang** [comment]
希望可以增加与印象笔记或有道笔记等软件挂靠的功能，以便保存卡包中学员感兴趣的文章，方便之后再次阅读。谢谢！

**Comment by oisy** [comment]
[网页端]
希望视频能有一个加快语速的功能，1.5倍或2倍（这个需求来自每个人吸收信息的速度不一样），谢谢。

**Comment by booox** [comment]
[Web页面]
希望添加用空格暂停及播放视频卡片的功能
（因为有时需要暂停视频查资料，或记笔记）

**Comment by serena333** [comment]
关于 App 有个小建议，现在翻卡片虽然顺畅，但是翻着翻着就不知道看的是正面还是反面了，也不知道哪些翻过背面哪些没翻过。卡片正反面是否可以用样式或者编号适当区分一下～

**Comment by Selaginella99** [comment]
@serena333 有一个技术问题，但那边好像被禁言了。“Markdown写作”卡包中卡片“Markdown语法概述”无法收藏，点击收藏标志无效。

**Comment by xuanmingzhang** [comment]
@Selaginella99 请问你用的是什么型号的手机及操作系统？如果收藏失败，您可以先关闭APP重新启动程序试试。

**Comment by xuanmingzhang** [comment]
@serena333 感谢建议，产品开发团队会对此进行讨论和分析，如有新的改进，会及时在 testflight 中让您更新。

**Comment by EattheSun** [comment]
卡片里面的网址不能复制或者分享，不便于电脑查看网址
很多内容需要在电脑上查看更方便，例如需要电脑操作的网站由于用超链接的形式无法知道网址，也就无法在电脑上操作，建议完善

**Comment by xiangshan** [comment]
机型：iPhone 6p
在App的“关于”里添加版本信息，或App内增加一个版本更新提示，比如在信箱📪打点⭕️，方便确认当前版本和更新。

**Comment by xuanmingzhang** [comment]
@xiangshan 多谢建议，版本更新日志会尽快纳入到APP里的相关位置。

**Comment by xuanmingzhang** [comment]
## 背景

- 期待实现的效果/欲达成的目的：使用App内的各种交互功能，如：选择/播放/下载/收藏/输入/提交
- 系统：Android 5.0.2
- 版本：开智学堂20160721更新
- 手机：乐1 PRO
- 学员：

## 现象

- 0w/1w所有卡包内的交互功能均无效
## 分析

- 尝试 0：
    - 参考：ipad上的开智学堂运行时交互功能正常
    - 判断：可能由ios版本编译为android版本代码中某些权限未打开或数据库链接bug
    - 实验：未实验
    - 结论：未知

## 方案

- 解决思路 0：更多在ipad上使用交互功能，在android上仅浏览；产品团队安卓应用正在优化和对具体机型做测试。

**Comment by Lamperouge1** [comment]
问题：开智APP-数据科学基础班第三期，卡包5数据科学导论-练习题4Simpson‘s Paradox-卡包背面点击参考：可视化展现Simpson’Paradox，出现错误信息：Erroe loading page
APP版本：IOS Version 2.6 Building 18
手机系统：IOS 9.3.5

**Comment by xuanmingzhang** [comment]
@Lamperouge1 在手机翻墙状态下用APP可以打开该地址 [可视化展现 Simpson's Paradox](http://vudlab.com/simpsons/)。建议在全局模式翻墙状态下用电脑查看。

**Comment by evonneK** [comment]
环境：IOS / iPhone 6 Plus

**问题： 视频课件横屏播放时，播放暂停键不灵敏**。
0次有9次点击了无法暂停，大拇指这种面积比较大的手指不行，必须食指指肚尖端垂直快速用力点击才能暂停成功。对于一边看视频，一边写代码的人来说，不能随意暂停，每次都得捧起手机认真戳暂停键的体验实在太糟糕了。

**Comment by xuanmingzhang** [comment]
@evonneK 谢谢反馈。听下来您的使用场景应该是把手机横屏放在键盘旁边，边看视频边写代码笔记，所以用拇指点暂停会更方便些。视频的操作体验在后期的版本会继续优化，请再给工程师童鞋们一些时间。

**Comment by evonneK** [comment]
问题：开智APP-数据科学基础班第三期，卡包5数据科学导论-练习题4Simpson‘s Paradox-卡包背面点击参考：可视化展现Simpson’Paradox，出现错误信息：Erroe loading page
手机系统：IOS 9.3.5

所有需要翻墙才能看的资料，可以在卡片上注明“需翻墙”吗？要看到这个issue页面才知道需要翻墙看，这个体验不是一般的差！

**Comment by xuanmingzhang** [comment]
@evonneK 谢谢反馈，这个建议已经发给负责课程卡片内容制作的同事，他们会逐渐给需要翻墙的资料注明的。

**Comment by ishanshan** [comment]
@evonneK  非常抱歉给你带来了不好的体验。已在卡片中增补说明，所有 data103 课程卡片中出现的链接，都可以在 Data103 课程仓库 wiki  《数据科学基础班涉及链接汇总》 文档中查看 ： https://github.com/OpenMindClub/Data103/wiki/IdxData103Reference 

数据科学课程涉及非常多国外资料、网站，比如你提到的 [可视化展现 Simpson's Paradox] http://vudlab.com/simpsons/  ，国内访问如果长时间无法加载，科学上网后加载速度能快些。

预祝学习愉快：）再有不顺，欢迎继续反馈。

**Comment by fffman** [comment]
关于开智世界项目的优化建议：

1、部落以后最好是有个地方让大家选择自己属于哪个大陆、部落（家族）、家族，设置好后，点击功能界面里的『部落』按钮就直接进入自己事先设置好的部落。

2、界面和配色还有待逐步优化，建议是风格参照开智公众号文章的设计风格，让大家在聊天时感觉就像是输出高质量的文字一样，内容或许跟不上，但是显示效果堪比正式编发的公众号文章。

3、以后选择完部落后，大家在群里聊天时，名字中会自动加上部落的前缀或后缀，比如说，我是西方大陆，那么我的名字就自然显示为【西方】倪考梦，或者倪考梦@西方，一个人的出身代表了他的血缘和地缘关系，给他归属感。早年电子竞技团队年代，我们战队成员都会在名字前加战队名的。

4、
