### ISSUE TITLE
新增功能类 问题汇总

### ISSUE THREAD

**Issue by badboy315** [OpenMindClub/OMC.App#25]
~ 用于产品新增功能收集

**Comment by eduream** [comment]
建议对卡片增加评论功能，或显示筛选后的学员评论。

**Comment by ouyangzhiping** [comment]
- [ ] Github 排名要启动了。  @ishanshan

**Comment by badboy315** [comment]
新增功能
- [ ] 1. APP 信息推送
- [ ] 2. 自定义头像
- [ ] 3. 管理后台
