### ISSUE TITLE
卡包解锁

### ISSUE THREAD

**Issue by layla1412** [OpenMindClub/OMC.App#26]
#16 
使用环境：qq浏览器、小米手机安卓系统 4.4.4KTU84p
触发情景描述：第五个卡包无法解锁。
![qq 20160315095602](https://cloud.githubusercontent.com/assets/17695078/13765414/2f5cd9a2-ea94-11e5-9220-40339bf78132.png)

**Comment by badboy315** [comment]
https://github.com/OpenMindClub/OMC.App/issues/21#issuecomment-196217644

已归档, 工程师处理中.

**Comment by MythJune** [comment]
iPhone 6S plus，系统版本9.2.1发现同样问题。
每一次到新卡包都无法解锁。

**Comment by badboy315** [comment]
@MythJune , 在发布下次新版本时, 这个问题会得到解决.

目前处理建议:
1. 确保上一个卡包的卡片都学习完, 查看进度;
2. 后台关掉 开智学堂app, 重启动 app, 即可恢复;

新产品目前存在诸多不足, 团队正在努力解决.
