### ISSUE TITLE
[windows]"什么是github"视频文件声音较低

### ISSUE THREAD

**Issue by zzk123456** [OpenMindClub/OMC.App#28]
* 系统版本：Windows7旗舰版
* 机型：电脑
* 使用环境：360极速浏览器
* 触发情景详细描述：
   1. 打开web版“开智学堂”
   2. 点击“卡包”选项卡
   3. 点击“领取装备”卡包
   4. 点击“什么是github”卡片
   5. Scott先生的讲解声音有点小啊

**Comment by badboy315** [comment]
收到.  工程师处理中.

**Comment by badboy315** [comment]
@zzk123456 已经处理完毕， 请重新进入查看。
