### ISSUE TITLE
讲义内容错误反馈

### ISSUE THREAD

**Issue by MissUUU** [OpenMindClub/OMC.App#29]
* 《开学典礼：无用的写作》中Github本版跟踪应为 `版本跟踪`

<img src="http://7xrxlq.com1.z0.glb.clouddn.com/%E8%AE%B2%E4%B9%89.jpg" width="500">

* 《心灵种种》中格列高**丽**心智应为`格列高利心智`

<img src="http://7xrxlq.com1.z0.glb.clouddn.com/%E6%A0%BC%E5%88%97%E9%AB%98%E4%B8%BD%E5%BF%83%E6%99%BA.jpg" width="500">

**Comment by ouyangzhiping** [comment]
很棒反馈，收到喽！ cc @xuanmingzhang  @cnfeat

**Comment by aJiea** [comment]
【写作之难】-【写作涉及的脑区过多】英文部分
- [ ]  Cognive control netwok 改为 Cognitive control network
- [ ] Sensory-motro networks 改为 Sensory-motor network

**Comment by ouyangzhiping** [comment]
@aJiea 多谢！收到！

**Comment by kt1130** [comment]
问题：授课视频错误
具体描述：心灵种种一课中，阳老授课视频的16分24秒出现的心智塔模型图片右侧的系统1——系统2似乎写反了，按照阳老的授课内容，应该是诞生于进化早期的心智属于系统1，诞生于晚期的心智属于系统2，所以应该是系统1在下面，系统2在上面。

**Comment by aJiea** [comment]
卡片排版
【极简写作训练法】之【翻译《老人与海》片段】
“hissingthat” 无空格，`` ..the hissing that... ``

**Comment by badboy315** [comment]
@kt1130 @aJiea 
收到， 感谢勘误。

**Comment by badboy315** [comment]
已修复
归档 https://github.com/OpenMindClub/OMAPP/issues/20
关闭 issue
