### ISSUE TITLE
web端[元技能卡包}的最后一张卡片点击无响应

### ISSUE THREAD

**Issue by MissUUU** [OpenMindClub/OMC.App#32]
**环境**：
* Chrome 49.0.2623.75

**前置条件**：
此卡包已在移动端[ios]下打开过并已完成课程

**重现步骤**：
1、web端进入开智学堂
2、卡包功能 - 元技能 - 倒数第五张卡片[开智元范：用绝对坐标沟通]
3、点击卡片

**问题**：
* 点击卡片无响应
* web端显示该卡片为最后一张卡片，无法下拉进入后面四张卡片

**备注**
* 移动端正常，无上述两个问题

**Comment by badboy315** [comment]
@MissUUU 状态:已修复. 建议: 多刷新页面即可.
