### ISSUE TITLE
Version 2.0.0 (15) 无法看到内容

### ISSUE THREAD

**Issue by bambooom** [OpenMindClub/OMC.App#33]
* 系统版本：ios 9.2.1
* 机型：iphone 6s
* 触发情景详细描述：刚刚更新 version 2.0.0 (15), 私享课的四个图标点击都没有反应. 底栏 `卡包` `视频` 点击后任何内容都看不到. `我`的卡包中, 点击任何一类卡包也看不到任何内容

**Comment by liuyi220** [comment]
5s也这样！

**Comment by myth8781** [comment]
我的手机htc也这样 电脑网页版现在也这样，昨夜开始的到现在状态一直没变。

**Comment by zoewang91** [comment]
系统版本：电脑MBP 2015
描述：网页版点击下方“卡包”，空白页，没有显示内容，手机端（安卓）可以显示

**Comment by ouyangzhiping** [comment]
辛苦 @badboy315  尽快处理。

**Comment by bambooom** [comment]
在主页左上角点击头像图标, 然后选择`退出登录` 后再重新登录, 可以解决
@liuyi220 @myth8781 @zoewang91

**Comment by badboy315** [comment]
@liuyi220 @myth8781 @zoewang91 
尝试 @bambooom 建议， 还可以重启 app 试下。 由于是第一版， 目前存在不足， 工程师正在迭代中。

ios 版 和 安卓版 也已经更新版本， ios 去 testfight 更新， 安卓版下载更新版 http://fir.im/9djt
