### ISSUE TITLE
[提交地址错误，请删除…… ]提升使用便利度的建议

### ISSUE THREAD

**Issue by MythJune** [OpenMindClub/OMC.App#34]
##  提议 1： 每周在APP某处有卡包数量+内容预告，便于学习者安排学习进度。 

优化的可能有：
*  在每周学习目标卡片中预告。 
*  通过APP定期推送通知。

## 提议2： 能不能详细解释一下 技术ISSUE, 优化ISSUE等issue命题的内涵和范畴，并举几个例子？有时候不知道该在哪里提建议……

**Comment by badboy315** [comment]
close
