### ISSUE TITLE
ios系统问题

### ISSUE THREAD

**Issue by yanlinson** [OpenMindClub/OMC.App#36]
## **[ios] app可进入但点击图标无反应**。
- 系统版本：ios 9.2.1
- 机型：iphone 6 plus

## **触发情景描述：**
- 点击进入app，再点击创作图标无反应。

**Comment by badboy315** [comment]
收到, 有按照 https://github.com/OpenMindClub/OMC.App/issues/35#issue-142356436 处理方法试过吗? 结果还是一样?

**Comment by badboy315** [comment]
@yanlinson

**Comment by yanlinson** [comment]
噢！ 已解决, 谢谢！

**Comment by yanlinson** [comment]
@badboy315
