### ISSUE TITLE
[web]卡包无法刷到下一个

### ISSUE THREAD

**Issue by wangyidong3** [OpenMindClub/OMC.App#37]
系统版本：OSX 10.10.5
使用环境：Safari 浏览器 8.0.8 、Chrome Version 48.0.2564.116 (64-bit)
触发情景详细描述：
第一周卡包只能刷到前10个。
截图：
![image](https://cloud.githubusercontent.com/assets/2003294/13944692/5fb08424-f042-11e5-9576-c7810e532c19.png)

刷新，强制刷新，重启，隐身模式，都试过。都不行。安卓APP总是死机，就更不行了。

**Comment by badboy315** [comment]
@wangyidong3 已建议 进入上一个卡包重新点击最后一张卡片后刷新。 按此处理，已解决。
