### ISSUE TITLE
打开web版开智学堂后没有卡包——BUG

### ISSUE THREAD

**Issue by Pziran** [OpenMindClub/OMC.App#38]
* 手机小米note
* 电脑win7+猎豹浏览器
* 使用移动数据，开热点上网

2016.3.21的时候可以正常使用
2016.3.２２的时候无法看到卡包，一片空白。（ｗｅｂ版和ａｐｐ版均试过）

**Comment by badboy315** [comment]
@Pziran 
收到反馈, 交由技术人员跟进.

**Comment by baishyue** [comment]
IOS主页进入开智APP屏幕上的按钮无法点击
机型：iPhone 6 plus
问题：点击开智App，进入APP首页后，除了页面下方“主页”“卡包”“视频”“我”之外，其余按钮点击均无反应。 页面下方四个按钮点击后，内容空白。
截图：

**Comment by badboy315** [comment]
@Pziran 已联系, 处理完毕, 如还有问题请再反馈.
