### ISSUE TITLE
Android卡包界面点进去卡死

### ISSUE THREAD

**Issue by jeromevc** [OpenMindClub/OMC.App#39]
系统版本：例如 Android （最新）

机型：oppo R5

触发情景详细描述：

APP 进入到卡包界面卡死。怎么拉都拉不下来。之前第一版本的时候就存在这个问题，后面全部卸载改用web 端，现在web端视频看不了(已经换用多个浏览器，包括内外网互切也没办法）所以重新下了APP，但是还是不行。

**Comment by badboy315** [comment]
@jeromevc 收到. web 界面建议使用 chrome 浏览器.

**Comment by badboy315** [comment]
@jeromevc 已联系.
