### ISSUE TITLE
WEB端卡包页面翻转出现的BUG

### ISSUE THREAD

**Issue by jeromevc** [OpenMindClub/OMC.App#40]
今天忘记个知识点，想重新去复习下，结果在点开卡包时候出现了类似的BUG。如图
![卡包页面翻转出现的BUG](http://ww2.sinaimg.cn/large/74311666jw1f2cd3chibcj20m808h74b.jpg)

PS：
Labels按钮在哪？

**Comment by badboy315** [comment]
@jeromevc 
1. 图片不是很清晰，请看下是哪个卡包里面的卡片吗？
2. 重新点击也会出现这个问题吗？

@cnfeat

**Comment by badboy315** [comment]
@jeromevc 已联系, 电脑配置问题.
