### ISSUE TITLE
不一定是bug，请工程师们看看

### ISSUE THREAD

**Issue by gunuo** [OpenMindClub/OMC.App#41]
手机apple 
在不同的网络环境切换时（从3G/4G换到wifi或者信号不好时），app有时候进得去，但最下面的卡包那一行无法出现。必须退出，等待一会儿，才能成功。
有几次进入电梯前开了app，然后出了电梯就不成了。
这种问题反复出现。
我不知道这算不算是bug。是不是信号接收的部分有些问题？
@zhangdian0801 @ZoomQuiet

**Comment by ZoomQuiet** [comment]
js 加载不完全...
俺的经验是:
如果流量充足,就关闭 wifi ,一直 4G
另外, 推荐用 safari 来看卡片,而不是app.

2016-03-30 23:52 GMT-05:00 毛颖 <notifications@github.com>:

> 手机apple
> 在不同的网络环境切换时（从3G/4G换到wifi或者信号不好时），app有时候进得去，但最下面的卡包那一行无法出现。必须退出，等待一会儿，才能成功。
> 有几次进入电梯前开了app，然后出了电梯就不成了。
> 这种问题反复出现。
> 我不知道这算不算是bug。是不是信号接收的部分有些问题？
> @zhangdian0801 <https://github.com/zhangdian0801> @ZoomQuiet
> <https://github.com/ZoomQuiet>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenMindClub/OMC.App/issues/41>
>



-- 
Life's Pathetic, Let's Pythonic! 人生苦短, Python是岸!
俺: http://zoomquiet.io
授: http://creativecommons.org/licenses/by-sa/2.5/cn/
怒: 冗余不做,日子甭过!备份不做,十恶不赦!
KM keep growing environment culture which promoting organization be
learnning!

**Comment by badboy315** [comment]
@gunuo 收到反馈. 可以按照 @ZoomQuiet 给的建议使用.

Safari 和 Chrome 都推荐使用的.
