### ISSUE TITLE
#42 攻城狮们，我有个小问题

### ISSUE THREAD

**Issue by yanlinson** [OpenMindClub/OMC.App#43]
- 机型：iphone 6 plus 
- 系统：ios 9.3.1 
最近工作忙, 抽不出时间来刷视频卡包, 请问课程结束后还能继续看视频, 做卡包练习吗? 谢谢。

@zhangdian0801 @ZoomQuiet

**Comment by zhangdian0801** [comment]
@yanlinson  课程结束后依然能反复观看，也欢迎继续提交作业并重新翻看 GitHub 上精华内容

**Comment by ZoomQuiet** [comment]
是也乎,(￣▽￣)
这就是 OM2py 的课程福利,,,
原有帐号一直有效,
以及更大的福利: 同侪关系!

On Mon, Apr 4, 2016 at 3:00 AM, zhangdian0801 <notifications@github.com>
wrote:

> @yanlinson <https://github.com/yanlinson> 课程结束后依然能反复观看，也欢迎继续提交作业并重新翻看
> GitHub 上精华内容
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenMindClub/OMC.App/issues/43#issuecomment-205182545>
>



-- 
Life's Pathetic, Let's Pythonic! 人生苦短, Python是岸!
俺: http://zoomquiet.io
授: http://creativecommons.org/licenses/by-sa/2.5/cn/
怒: 冗余不做,日子甭过!备份不做,十恶不赦!
KM keep growing environment culture which promoting organization be
learnning!
