### ISSUE TITLE
501 卡片内容歧义

### ISSUE THREAD

**Issue by xiaojingli** [OpenMindClub/OMC.App#44]
今天（5W6）阳老答疑中提到有同学把修辞的人文路径和文体路径对应于中国的“修辞以立其诚”和西方的“修辞以立其真”，但事实上东西方传统修辞学中都存在人文路径和文体路径的矛盾。

我看了一下卡片，在501（好文采，坏文采）这个卡包里，能量卡“写作窍门：修辞以立其感”中出现了类似的表述。
<img width="790" alt="2016-04-16 9 38 06" src="https://cloud.githubusercontent.com/assets/11477264/14583228/90c7ad66-041b-11e6-9158-5049725f302f.png">

不知道是不是这个总结引起了大家的误解。可否麻烦修改一下表述？以消除歧义？

**Comment by cnfeat** [comment]
已修复完成以下内容：

传统修辞有两条路径，一条是以中国为代表的人文路径——修辞以立其诚，即求修辞者持中正之心，怀敬畏之情，对自己的言辞切实承担责任，采用最好的方式予以表达，并预期达致成功。

另一条是以西方为代表的文体路径——西方修辞以立其真，提倡研究以事实为根据、富有逻辑力量的说服论证，通过诉讼演说获得公正、适当的判决，并且可将这种说服论证应用于政治机构的议事演说和公民大会演说。

本节课提倡的是第三条路径——修辞以立其感，忽视传统修辞的分类与意义，鼓励以语言感觉为依据，用新的目光，讨探出古老的修辞学所不曾觉到的意义。

各位尝试在写作语言中注入感觉，赋予文本更多的色彩与姿态。
