### ISSUE TITLE
web版App  视频声音很小，且音质模糊

### ISSUE THREAD

**Issue by meleslilijing** [OpenMindClub/OMC.App#45]
web版视频声音很小，且音质模糊。

测试视频地址：http://openmindclub.com/#/frame/card_video_new/3f123330-ffe1-11e5-a837-0800200c9a66//8785d3e0-0a8d-11e6-b782-b7bcf283efa5

已确认打开网页声音
已确认打开电脑/手机的声音

系统版本：win7, OSX 10.10.5，IOS 8
移动端机型：iPhone 5s
使用环境：Chrom，Safari, FF， Safari

**Comment by yangshaoshun** [comment]
@meleslilijing 你好，感谢你的反馈。
这个视频本身是测试视频，声音很小，且有很多杂音。
不知道你有没有测试过其他的视频文件，也存在类似的问题吗？
比如说这个 [课程概览及介绍](http://openmindclub.com/#/frame/card_video_new/3f123330-ffe1-11e5-a837-0800200c9a66//88271cf0-0a8d-11e6-b782-b7bcf283efa5)

**Comment by badboy315** [comment]
经确认，单个视频文件存在问题。目前工程师修复中。
