### ISSUE TITLE
Web 端测试页面卡包打开不全

### ISSUE THREAD

**Issue by serena333** [OpenMindClub/OMC.App#48]
- 使用环境：Mac , Chrome Version 50.0.2661.102 (64-bit)
- 触发情景详细描述：
    - 点击 GitHubWeb 卡包，查看了15张卡片就到“欢迎进入下一章节”的卡片并且无法点击，卡包显示 15/24
    - 退出重新登录，再次进入卡包，中间又加载出7张卡片，卡包显示 22/24 ，看不到没有加载出的 2 张卡片，也无法进入下一关
    -  再次登录，没有反应
![2016-05-23 6 28 45](https://cloud.githubusercontent.com/assets/17064496/15457618/30884ec2-20bf-11e6-8605-d96f8f973ec8.png)

**Comment by xuanmingzhang** [comment]
解决方案汇总：

1. 刷新页面
2. 退出浏览器账号，重新登录
3.用手机Safari或其他手机浏览器登录，体验和APP一样流畅
4.联系管理员用新账号登录，登录后没有遇到问题后退出账号重新登录个人账号

已更新到：[开智学堂 APP 下载及常见问题自测处理 · Issue #9 · OpenMindClub/Hacker](https://github.com/OpenMindClub/Hacker/issues/9)
