### ISSUE TITLE
[Android]+无法播放视频

### ISSUE THREAD

**Issue by riverphoenix17** [OpenMindClub/OMC.App#50]
系统版本： Android 6.0.1
机型：三星s7 edge
 触发情景详细描述：点击GitHubWeb、GitHub桌面版、Git命令行等卡包中的视频没有反应

**Comment by xuanmingzhang** [comment]
视频无法播放，请尝试以下步骤：

1.退出APP重新登录
2.删掉APP，通过[http://fir.im/tc27](http://fir.im/tc27)重新下载
