### ISSUE TITLE
encoding，把string转化为num的问题

### ISSUE THREAD

**Issue by sharlynx** [OpenMindClub/OMC.App#51]
Title：把dataframe当中的string内容转化为数字，用作后面的聚类分析用

背景：python 2.7, Mac OS X EI Capitan

![image](https://cloud.githubusercontent.com/assets/16401707/16605277/1630b1ea-4360-11e6-924b-1243b6ff20af.png)

原始表格中，有一列type，希望把type中的不同类型转化成数字，比如，小吃快餐 = 1， 川菜=2，形成一个新的column。

`shopdic = {
    u"小吃快餐": 1,
    u"面包甜点": 2,
    u"日本菜": 3,
    u"西餐": 4,
    u"咖啡厅": 5,
    u"本帮江浙菜": 6,
    u"火锅": 7,
    u"粤菜": 8,
    u"川菜": 9}`

目前做了一个dictionary，然后用map来做，tdf是表名。

`new_dict = {k: v for k, v in shopdic.iteritems()}`
`tdf['newtype'] = tdf['type'].map(new_dict)`

报错：
//anaconda/lib/python2.7/site-packages/pandas/indexes/base.py:2028: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  indexer = self._engine.get_indexer(target._values)

![image](https://cloud.githubusercontent.com/assets/16401707/16605332/9abb938a-4360-11e6-913d-a4a21bad8a3b.png)

## 但是！如果是我自己在python里面创建一个新的有中文字的表格，用这种方法，就没问题

所以是原来的tdf表格有问题么？我把tdf表格用encoding='utf'编码之后，也还是不行。

所以不知道应该怎么办了。求助。

**Comment by ishanshan** [comment]
@sharlynx 问题提交错地方了哦，课程学习疑问提交到课程仓库 [Issues · OpenMindClub/Data102](https://github.com/OpenMindClub/Data102/issues)
