### ISSUE TITLE
安卓版APP播放完视频后无法恢复竖屏

### ISSUE THREAD

**Issue by chousawa** [OpenMindClub/OMC.App#52]
- 系统：Android 6.0.1
- 手机型号：小米note
- 触发：在看完视频退出后显示页面仍然是横屏，无法恢复竖屏

![screenshot_2016-07-06-15-56-06_com anrenmind open](https://cloud.githubusercontent.com/assets/16424679/16611311/138d050a-4393-11e6-9169-46d4bbff6178.png)

**Comment by xuanmingzhang** [comment]
感谢反馈，请尝试关闭应用后重新打开，看是否还存在该问题。

**Comment by xuanmingzhang** [comment]
该问题已经经过工程师修复，请留意 testflight 邮件的版本更新提示。 @chousawa
