### ISSUE TITLE
苹果6s手机在4G的环境下点击播放视频自动闪退

### ISSUE THREAD

**Issue by chilimin** [OpenMindClub/OMC.App#53]
苹果6s手机在4G的环境下点击播放视频自动闪退，我尝试了关掉APP，重启，关掉手机重启，都还是不行。wifi环境下没有问题，我需要在4G环境下看，有时间的时候很难有wifi，对我来说4G很重要。

## 背景

- 期待实现的效果/欲达成的目的：正常播放
- 系统：
- 版本：

## 现象

- 输入：……
- 触发：……（最好能附图说明）
- 问题：非期待……

## 分析

- 尝试 0：
    - 参考：(请给出检索到的参考文档链接，请优先使用官方文档)
    - 判断：
    - 实验：
    - 结论：
- 尝试1：
- ……

## 方案

- 解决思路 0：
    - 参考：(请给出检索到的参考文档链接，请优先使用官方文档)
    - 设想：
- 解决思路 1：
……

依然没有解决，请求帮助。

	注意：问题解决后
	
	1. 题主需更新可用的解决方案在首个 comment 中，以便后来的同伴参考
	2. 点击 Issue 下方右下角 close issue 归档

**Comment by yangshaoshun** [comment]
@chilimin 该 bug 已经验证，工程团队积极处理中，请留意 testflight 的版本更新提示。

**Comment by chilimin** [comment]
解决了
