### ISSUE TITLE
【bug】ios 创作里面的视频没有声音

### ISSUE THREAD

**Issue by 13416136446** [OpenMindClub/OMC.App#54]
Title：卡包第二个里面的两个视频都没有声音

## 背景

- 期待实现的效果/欲达成的目的：最后可以有调节音量的按钮以及显示音量的地方
- 系统：
- 版本：

## 现象

- 输入：……
- 触发：……（最好能附图说明）
- 问题：非期待……

## 分析

- 尝试 0：
    - 参考：(请给出检索到的参考文档链接，请优先使用官方文档)
    - 判断：
    - 实验：
    - 结论：
- 尝试1：
- ……

## 方案

- 解决思路 0：
    - 参考：(请给出检索到的参考文档链接，请优先使用官方文档)
    - 设想：
- 解决思路 1：
……

依然没有解决，请求帮助。

	注意：问题解决后
	
	1. 题主需更新可用的解决方案在首个 comment 中，以便后来的同伴参考
	2. 点击 Issue 下方右下角 close issue 归档

**Comment by xuanmingzhang** [comment]
@13416136446 如果iOS系统下视频没有声音，请先查看是否开启了静音功能，或者尝试用耳机测试能否听到声音。

执行以上步骤后仍然无法听到声音请关闭APP重新打开，或者删掉APP，通过 TestFlight重新下载。

如果仍然无法解决问题，请在这里反馈。
