### ISSUE TITLE
卡片里面的超链接网址不能复制或者分享，不便于电脑查看网址和做笔记

### ISSUE THREAD

**Issue by EattheSun** [OpenMindClub/OMC.App#55]
机型：iphone 6s p
系统：iOS 9.3.2
开智学堂app版本：2.5(3)
卡片里面的超链接网址不能复制或者分享，不便于电脑查看网址和做笔记

**Comment by yangshaoshun** [comment]
多谢您的建议，我们会在下一版本中考虑这个需求
