### ISSUE TITLE
[Android]认知写作第三期课程点击“开始上课”时自动退出

### ISSUE THREAD

**Issue by GardenWPY** [OpenMindClub/OMC.App#56]
#### 机型：红米note3
使用环境：开智学堂APP 版本：2.5（Build 5）
触发情景详细描述：
## 第一种尝试
经过了步骤1
#### 点击了“开智私享课”栏内的“创作”
步骤2
#### 点击“认知写作学三期”
步骤3
#### 点击蓝色按键“开始上课”之后，出现了自动退出
截图：
![image](https://cloud.githubusercontent.com/assets/19836458/16934815/c2e60b70-4d8c-11e6-8ebe-64b64f6eb8fc.png)

![image](https://cloud.githubusercontent.com/assets/19836458/16934650/f44c91e0-4d8a-11e6-9ed7-c18b9bb7769e.png)
![image](https://cloud.githubusercontent.com/assets/19836458/16934689/4ec32b16-4d8b-11e6-9682-480641891bd4.png)
![image](https://cloud.githubusercontent.com/assets/19836458/16934751/1b11d406-4d8c-11e6-910a-9682082c4f3c.png)

## 第二种尝试
在“我的课程”里点选“认知写作学三期”，直接自动退出。
![image](https://cloud.githubusercontent.com/assets/19836458/16934802/9b02b342-4d8c-11e6-8e5b-15f962415554.png)

## 第三种尝试
重新下载安装APP，依旧出现上述问题。

@ 开智学堂-北京-张轩铭

PS：无权限编辑这个issues的“labels”

	注意：问题解决后
	
	1. 题主需更新可用的解决方案在首个 comment 中，以便后来的同伴参考
	2. 点击 Issue 下方右下角 close issue 归档

**Comment by xuanmingzhang** [comment]
@GardenWPY 问题已经收到，工程师正在加紧排查问题，请耐心等候。如果您有iOS设备，我们可以发送iOS程序下载链接给你继续学习。您也可以先登录 tv.openmindclub.com 进行视频学习。

**Comment by xuanmingzhang** [comment]
@GardenWPY 很抱歉「APP闪退」这个bug为您的正常学习带来影响，在开智工程师的紧急抢修之后，问题已经解决。您可以 通过 http://fir.im/9l5s 更新安卓应用。祝您学习愉快~

**Comment by GardenWPY** [comment]
谢谢^_^版本更新后能正常使用。

**Comment by wqchic** [comment]
我之前也经历过闪退，请问要如何做版本更新呢？

**Comment by xuanmingzhang** [comment]
@wqchic  通过手机浏览器 打开以下网址：http://fir.im/9l5s ，按照手机提示一步步安装即可。
