### ISSUE TITLE
黑客二期课程卡包“电子书制作知识扩展”中视频卡片无法播放

### ISSUE THREAD

**Issue by summerpenguin** [OpenMindClub/OMC.App#57]
Title：黑客二期课程卡包“电子书制作知识扩展”中视频卡片无法播放
## 背景
iPhone 6 手机
## 现象
黑客二期课程卡包“电子书制作知识扩展”中”GitBook CLI & 电子书制作“这张视频卡无法播放，点击之后会跳转到该卡包的最后一张卡片。

![](http://i2.piimg.com/567571/f334f97226c3527a.jpg)

![](http://i2.piimg.com/567571/55dd1beecf562d9e.jpg)

请求帮助。

**Comment by xuanmingzhang** [comment]
更新APP后已修复该问题。
