### ISSUE TITLE
【认知写作学】内容错误。

### ISSUE THREAD

**Issue by Wangjunyu** [OpenMindClub/OMC.App#58]
位置：卡包中“我们赖以生存的隐喻”，402.用抽象比喻具体的小作业的背面
![问题图片](http://oa1mlhrmq.bkt.clouddn.com/writer003/bug-report.jpg)
内容错误如图。

**Comment by xuanmingzhang** [comment]
@Wangjunyu 内容已更正，多谢指出卡片的不当之处。欢迎多多反馈，你的建议可以让同学们享受到更好的学习体验。
