### ISSUE TITLE
【认知写作学】卡包中视频突然没有声音

### ISSUE THREAD

**Issue by sophyer-on-the-way** [OpenMindClub/OMC.App#59]
- IPad mini2，系统版本 iOS 9.3.2（13F69)）
- 第五讲第四关《时空变形技法·下》③视频05:00小结开始后没有声音，其他皆正常。

**Comment by xuanmingzhang** [comment]
@sophyer-on-the-way 感谢反馈，用iPhone测试后发现了同样的情况，稍后会联系视频制作人员解决该问题。

**Comment by xuanmingzhang** [comment]
@sophyer-on-the-way 视频没有声音的问题已经解决，请继续使用，加油学习！
