### ISSUE TITLE
[feedback]北京同侪汇芝麻星系统反馈

### ISSUE THREAD

**Issue by cnfeat** [OpenMindClub/OMC.App#6]
2015-10-17 
在北京同侪汇上介绍芝麻星系统，并现场采访北京线下学员，结果如下：

- 大部分学员刚开始使用芝麻星，少部分已开始深挖
- 使用过的同学普遍好评，基本可以找到需要的信息，例如视频回放，任务接收等

使用场景及反馈：

- 线下学员大多从网页打开芝麻星
- 使用网页版原因：学员需要一边看任务，一边编程，一边打开参考链接学习
- 打开参考链接会自动跳转页面，而不是新打开页面，返看任务麻烦
- 网页打开卡片感不强
- 芝麻星md 渲染体验尚待改良，例如缩进显示凌乱和不能显示图片

建议

- 适当优化网页版
- 参考链接设置新打开
- 加强 md 渲染效果

**Comment by ishanshan** [comment]
过期关闭
