### ISSUE TITLE
[Android]+登录APP时提示"未知错误"

### ISSUE THREAD

**Issue by YuMount** [OpenMindClub/OMC.App#60]
Title：[Android]+登录APP时提示"未知错误"

## 现象和解决尝试

- 系统版本：Android4.4.2 Smartisan OS v2.6.8
- 机型：Smartisan T1
- 触发环境描述：
   -  第一步，打开APP时卡在打开时的画面，时间半小时左右。
   -  第二步，后台结束任务，重新登录，仍然卡在初始画面。
   -  第三步，后台结束任务，重启手机，重新登录，仍然卡在初始画面。
   -  第四步，卸载APP，重新登录，进入登录界面，输入手机号和密码后，提示“未知错误”，截图如下：
![77](https://cloud.githubusercontent.com/assets/20666603/18075162/ff3e0986-6ea4-11e6-8f75-92af2a6d3855.jpg)

   -  第五步，卸载APP，重启手机，重新安装，打开，进入登录界面，输入手机号和密码后，提示“未知错误”截图如第四步所示。

依然没有解决，请求帮助。

Labels: bug smartisan

**Comment by xuanmingzhang** [comment]
@YuMount 检测之后发现是密码有问题，为你重置了密码为 openmind ，我这边用真机测试后登陆成功。请尝试重新登录。

**Comment by YuMount** [comment]
好的，问题已解决。多谢了。
