### ISSUE TITLE
[Android5.0.2]部落进入开智世界闪退

### ISSUE THREAD

**Issue by spring-Lyn** [OpenMindClub/OMC.App#62]
## 背景

Android5.0.2系统，华为荣耀7

## 现象

开智APP，点击「部落」正常进入，点击「开智世界」闪退。写作课卡包能正常使用，尝试重新登录及重新安装APP，无果。

**Comment by MatrixXT** [comment]
### 闪退
* 系统版本：Android 4.4.2、EMUI Version 3.0
* 机型：华为荣耀6
* 触发情景与楼上相同

**Comment by wangh0117** [comment]
* 背景 ：emui3.1系统，华为荣耀7

* 现象：与 @spring-Lyn 相同

**Comment by xuanmingzhang** [comment]
@spring-Lyn @MatrixXT @wangh0117 各位遇到的闪退问题已经反馈给工程师，他们正在处理，请等待新版本。

**Comment by pengjia37** [comment]
系统：安卓5.1.1 坚果手机
现象：进入我的课程中开智世界，新手村，通识部落，点击视频，均会出现闪退
