### ISSUE TITLE
IOS系统，APP里没有了以前的认知写作二期课程

### ISSUE THREAD

**Issue by luckth** [OpenMindClub/OMC.App#63]
Title：(一句话问题描述，最好能简要描述清楚操作和返回结果)

## 背景

- 期待实现的效果/欲达成的目的：
- 系统：
- 版本：

## 现象

- 输入：……
- 触发：……（最好能附图说明）
- 问题：非期待……

## 分析

- 尝试 0：
    - 参考：(请给出检索到的参考文档链接，请优先使用官方文档)
    - 判断：
    - 实验：
    - 结论：
- 尝试1：
- ……

## 方案

- 解决思路 0：
    - 参考：(请给出检索到的参考文档链接，请优先使用官方文档)
    - 设想：
- 解决思路 1：
……

依然没有解决，请求帮助。

	注意：问题解决后
	
	1. 题主需更新可用的解决方案在首个 comment 中，以便后来的同伴参考
	2. 点击 Issue 下方右下角 close issue 归档

**Comment by yangshaoshun** [comment]
检查了数据库，你的账号有 认知写作学二期 权限

路径为： 「我的课程 - 完结课程 - 认知写作学二期」

推荐到 Appstore 更新 开智学堂 App 到最新版本

* [开智学堂 on the App Store](https://itunes.apple.com/us/app/kai-zhi-xue-tang/id1090387756?mt=8)

**Comment by luckth** [comment]
已下载最新版本，点击【我的课程-完结课程】，里面为空。在此之前我重新申请过密码，会不会被系统默认为新用户了？

**Comment by yangshaoshun** [comment]
检查过后台，确定你的账号没问题，你可以 重新登陆 试试看
