### ISSUE TITLE
[iOS]重复进入相同卡包后，界面停留在最末尾的一张卡片而非上一次所读的卡片

### ISSUE THREAD

**Issue by RamyWu** [OpenMindClub/OMC.App#64]
## 背景

- 系统：iOS9.2
- 机型：iPhone6

## 现象

1. 打开已经完成阅读的卡包
2. 进入后，总停留在最后的卡片位置
3. 需要左滑倒退到之前的卡片位置
4. 期待是进入上一次阅读的卡片位置

**Comment by yangshaoshun** [comment]
目前的逻辑是：

* 刷完的卡包，即复习时：进入为该卡包的第一张卡片
* 正在进行的卡包：进入为上一次阅读卡片的位置

我们会在下一版本中考虑你提出的问题，多谢你的反馈
