### ISSUE TITLE
[iOS]打开卡包，快速滑动卡片，界面卡死

### ISSUE THREAD

**Issue by RamyWu** [OpenMindClub/OMC.App#65]
## 背景

- 系统版本：iOS9.2
- 机型：iPhone6

## 现象

- 输入：快速滑动卡片
- 触发：界面卡死，卡片无法滑动

## 分析

- 尝试 0：
    - 参考：(请给出检索到的参考文档链接，请优先使用官方文档)
    - 判断：
    - 实验：
    - 结论：
- 尝试1：
- ……

## 方案

- 解决思路 0：
    - 参考：(请给出检索到的参考文档链接，请优先使用官方文档)
    - 设想：
- 解决思路 1：
……

依然没有解决，请求帮助。

	注意：问题解决后
	
	1. 题主需更新可用的解决方案在首个 comment 中，以便后来的同伴参考
	2. 点击 Issue 下方右下角 close issue 归档

**Comment by yangshaoshun** [comment]
快速滑动卡片卡死，可能是由于网络连接带来的，因为每张卡片都需要从云端下载

多谢你的反馈
