### ISSUE TITLE
BUG:[Android]+点击底部导航「卡包」，白屏 

### ISSUE THREAD

**Issue by zhangshiyinrunwithcc** [OpenMindClub/OMC.App#68]
Title：([Android]+点击底部导航「卡包」，白屏)
背景

    期待实现的效果/欲达成的目的：选择底部导航「卡包」 ，有如下图的效果
![04](https://cloud.githubusercontent.com/assets/19412465/19544844/65a91dd2-96b4-11e6-86fd-21dc7e6bdcd8.png)

    系统：MIUI8.0.6.0
    版本：3.0 (Build 27)

现象

    输入：点击底部导航「卡包」
    触发：白屏（最好能附图说明）
![03](https://cloud.githubusercontent.com/assets/19412465/19544856/77f2b3fe-96b4-11e6-8af2-90431e0d1cab.png)

    问题：底部导航「卡包」没有任何内容 

## 分析

- 尝试 0：
    - 参考：(请给出检索到的参考文档链接，请优先使用官方文档)
    - 判断：
    - 实验：
    - 结论：
- 尝试1：
- ……

## 方案

- 解决思路 0：
    - 参考：(请给出检索到的参考文档链接，请优先使用官方文档)
    - 设想：
- 解决思路 1：
……

依然没有解决，请求帮助。

	注意：问题解决后
	
	1. 题主需更新可用的解决方案在首个 comment 中，以便后来的同伴参考
	2. 点击 Issue 下方右下角 close issue 归档

**Comment by yangshaoshun** [comment]
原因同 #67 ，请微信联系「一休」处理。
