### ISSUE TITLE
BUG:[iOS]+ipad无法横屏且无法播放视频

### ISSUE THREAD

**Issue by wangshuoyang** [OpenMindClub/OMC.App#69]
Title：(BUG：iOS+ipad无法横屏且无法播放视频)

## 背景

- 期待实现的效果/欲达成的目的：APP可以在ipad pro上横屏使用，且能播放视频。
- 系统：ios 10.0.2(14A456)
- 机型：iPad Pro MLMQ2CH/A

## 现象

- 输入：打开APP
- 触发：无论如何旋转pad
- 问题：app都不能横屏。且app中视频无法打开。

## 分析

- 尝试 0：
    - 参考：
    - 判断：
    - 实验：
    - 结论：
- 尝试1：
- ……

## 方案

- 解决思路 0：
    - 参考：(请给出检索到的参考文档链接，请优先使用官方文档)
    - 设想：
- 解决思路 1：

依然没有解决，请求帮助。

**Comment by xuanmingzhang** [comment]
@wangshuoyang 请问是所有视频都无法打开，还是说开智部落的视频无法打开？

**Comment by wangshuoyang** [comment]
@xuanmingzhang 是卡包里的视频打开不了。

**Comment by linfeng365** [comment]
昨天 视频直播，一打开就闪退了。iPhone 6s iOS 10.0.2

**Comment by yangshaoshun** [comment]
@wangshuoyang 目前 app 暂不支持横屏使用，视频播放的问题，可能是网络环境较差造成的。可以试试登陆 tv.openmindclub.com 观看卡包中的视频。

**Comment by yangshaoshun** [comment]
@linfeng365 以后提问题建议单独开 isuuse 哦
点击 「视频直播闪退」 的问题，可能是 APP 没有更新到最新版的原因，已给你发了最新版app 的 testflight 邮件，请先更新到最新版。

然后你可以到「开智世界」卡包中，去观看昨天下午的直播回放
