### ISSUE TITLE
晚来的芝麻星测评

### ISSUE THREAD

**Issue by aJiea** [OpenMindClub/OMC.App#7]
1. 新用户和登录
- 非github用户如何注册？首页无【注册新帐号】入口？是否因为对加入会员有限制所以故意无涉及？
- 记住我的登录状态，不用每次点【github登录】，不知是不是安全问题没有连接？

2. PC & 移动 界面包装
PC
北京线下反馈很多用PC开机浏览。如果屏幕长，阅读起来可以做左右颈部运动。1234-2234-3434。是否考虑背景不变，将重要信息居中？而且卡片，也更具有卡片感。 可以参考chrome +新标签窗口，重要信息居中排版，三国杀游戏界面，居中和留白关系。（可放大） http://web.sanguosha.com/  
移动端优化（不必须）：转发的时候无缩约图和介绍
![88979407356490004](https://cloud.githubusercontent.com/assets/13810631/10660867/c1a810c6-78dc-11e5-8b3c-d08e20118fa7.jpg)

3.路线
【课程-卡包-卡包列表-卡片】
- 直接从卡片不能返回卡包；进入卡包后不能返回课程
- 进入卡片后，无通道连接我的卡包
【我的卡包- 收藏的卡包】
- 我的卡包有重复两页
- 进入收藏卡包后无返回按钮

4.用户化&个性化
- 收藏卡片后将其用自己的语言备注功能，也会便于搜索
- 建议左侧开竖栏，采用卡包目录形式，直接跳转，也让卡片的所属条理更加清晰
- 翻转卡片提交任务进度，感觉平台是鼓励用户对任务进行打卡，那么是否出一个地方，直接进入未打卡项目，关联本周需要打卡的任务，这种提示比大妈口催更加醒目，更强迫症

综上所诉让芝麻星更加用户化，登录后无论进入哪里，界面一直需要保留的内容有：
【我收藏的卡包】
【任务提醒】
【卡片快速通道】目录

ps 芝麻星作为一个产品的logo和英文名？Sesame Galaxy?(这么这么眼熟)

**Comment by aJiea** [comment]
@ishanshan 

一个界面四卡包，卡是越来越多的。
- 是按照卡片的思维来排序，符合卡片设置的逻辑，抑或
- 按照用户使用优先级来排序，如：和当前课题相关的，1w2w卡包，避免翻页寻找

**Comment by tonyyet** [comment]
@aJiea 

谢谢如此精彩的反馈！

我尝试逐一回复：

> 非github用户如何注册？首页无【注册新帐号】入口？是否因为对加入会员有限制所以故意无涉及？

芝麻星系统是跟线下课程捆绑的，我们开放的第一个课程是python入门课，因为编程嘛，用github登入，乃最方便也，你在github的课程commit记录，我们也容易记录，继而做成leader board.

> 记住我的登录状态，不用每次点【github登录】，不知是不是安全问题没有连接？

这是github的 OAuth，只需一次认证，不需要每次都重复认证的。

> 北京线下反馈很多用PC开机浏览。如果屏幕长，阅读起来可以做左右颈部运动。1234-2234-3434。是否考虑背景不变，将重要信息居中？而且卡片，也更具有卡片感。 可以参考chrome +新标签窗口，重要信息居中排版，三国杀游戏界面，居中和留白关系。（可放大） http://web.sanguosha.com/

嗯，芝麻星优先为移动设备设计的，但用电脑打开应当也没有问题。在往后的版本里，对UX会做出改进。

> 直接从卡片不能返回卡包；进入卡包后不能返回课程
> 进入卡片后，无通道连接我的卡包 【我的卡包- 收藏的卡包】
> 我的卡包有重复两页
> 进入收藏卡包后无返回按钮

是也乎。也是UX的问题，后续版本会加以改善。

> 收藏卡片后将其用自己的语言备注功能，也会便于搜索

备注功能！嗯，这个我们没有想到呢。我们先试试，假如确实有很多人有这方面需求，我们加进去。

> 建议左侧开竖栏，采用卡包目录形式，直接跳转，也让卡片的所属条理更加清晰

Got!

> 翻转卡片提交任务进度，感觉平台是鼓励用户对任务进行打卡，那么是否出一个地方，直接进入未打卡项目，关联本周需要打卡的任务，这种提示比大妈口催更加醒目，更强迫症

Good idea! 

> 芝麻星作为一个产品的logo和英文名？

Logo 即将出炉，英文名是 Zhi Ma Star :)

**Comment by aJiea** [comment]
【卡包】-【卡片】
一个卡包里的卡片都已学习rate完=知识已经掌握，该卡包封面是否可以用阴影颜色标示，以和未进行完的卡包做出区分？提示学员，这个卡包已经学习完了，需要继续学习的应该是还处于白色背景的卡包。

**Comment by tonyyet** [comment]
这个关于颜色的建议有意思，谢谢。

不过，假如你说的是记忆卡，其原理是希望你不定期反复对其进行复习，以加深掌握的。因为人的记忆太不靠谱了，你今天记住的东西，可能过两周就忘记了，所以呢，反复记忆，间隔记忆，都是必要难度，都很必要！

2015-10-24 7:26 GMT+08:00 aJiea <notifications@github.com>:

> 【卡包】-【卡片】
>
> 一个卡包里的卡片都已学习rate完=知识已经掌握，该卡包封面是否可以用阴影颜色标示，以和未进行完的卡包做出区分？提示学员，这个卡包已经学习完了，需要继续学习的应该是还处于白色背景的卡包。
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenMindClub/zhimastar/issues/7#issuecomment-150714990>
> .
>



-- 
Tony Yet
tonyyet.com
HK: +852 9254 7108
Guangzhou: +86 156 2516 1449

**Comment by aJiea** [comment]
想起一个软件叫DUOLINGO，语言学习卡片制的，完成卡包学习后卡包会变成绿色，过一段时间不去复习，卡包颜色会退成橙色，然后到红色。不知是否有参考性

**Comment by bambooom** [comment]
>
>> 记住我的登录状态，不用每次点【github登录】，不知是不是安全问题没有连接？
> 
> 这是github的 OAuth，只需一次认证，不需要每次都重复认证的。

这里我还表示疑问，我以为 @aJiea 的问题是说每次重新打开芝麻星的页面就要重新登陆，不会记住登陆状态。的确不用每次重新认证，只是每次要重复点击“登陆”。

有关颜色卡片，我也觉得需要> <，因为会忘记自己看到哪里，当然重新看倒也没什么问题。哪些是从来没点开看的还是可以明示一下吧。。。。或者可以看过多少次就变成什么颜色之类的？

**Comment by tonyyet** [comment]
> 【工具栏固定】
> 建议固定上下工具栏，上面工具栏不因浏览下拉而被刷走，因为上栏反面卡片功能和退出功能为常用。

这个建议很好，谢谢 @aJiea !

芝麻星后续的版本会加上这个功能。

**Comment by ishanshan** [comment]
过期关闭
