### ISSUE TITLE
BUG:[Android]+查看“部落-开智世界”的聊天后一直闪退

### ISSUE THREAD

**Issue by pengjia37** [OpenMindClub/OMC.App#70]
## 背景

- 期待实现的效果/欲达成的目的：查看“部落-开智世界”的聊天
- 系统：安卓5.1.1
- 版本：Smartisan os v2.6.8

## 现象

- 输入：点击部落-开智世界
- 触发：一直闪退，进不去（之前无此问题，今天才有）
- 问题：

## 分析

- 尝试 0：
    - 参考：(请给出检索到的参考文档链接，请优先使用官方文档)
    - 判断：
    - 实验：
    - 结论：
- 尝试1：
- ……

## 方案

- 解决思路 0：
    - 参考：(请给出检索到的参考文档链接，请优先使用官方文档)
    - 设想：
- 解决思路 1：
……

依然没有解决，请求帮助。

	注意：问题解决后
	
	1. 题主需更新可用的解决方案在首个 comment 中，以便后来的同伴参考
	2. 点击 Issue 下方右下角 close issue 归档

**Comment by newjueqi** [comment]
我的手机也是这样，估计是收到某条部落-开智世界”的聊天消息造成app异常。
系统：安卓4.4.2
版本：华为荣耀4x

**Comment by xuanmingzhang** [comment]
@newjueqi 该问题已经解决，点击[开智学堂 ](http://fir.im/9l5s)重新下载安装即可。
