### ISSUE TITLE
[iOS]登陆更新后的APP后无法播放卡包中的视频课程

### ISSUE THREAD

**Issue by youngyoungyy** [OpenMindClub/OMC.App#72]
Title：用苹果手机下载开智学堂最新版的APP并登陆后，就无法播放卡包里的视频课程了，之前旧APP版本一直是正常播放的
- 系统 版本：iOS 10.1.1
  机型：iphone5S
为收看开智部落的直播，本人删除了苹果手机里之前旧版本的开智APP，下载了最新版本，登陆成功后看完了直播，然后点击里面的课程卡包，发现只有文字正常显示，视频全部不能收看。包括认知写作学课程卡包里之前正常收看过的视频课程，以及开智部落卡包里的视频。

**Comment by xuanmingzhang** [comment]
你好，app 暂时还不支持最新版iOS 10.1.1，工程师正在加紧时间升级中。在app完成升级前，你可以先用浏览器登录 tv.openmindclub.com 查看所有视频。
