### ISSUE TITLE
IOS 10.0.2 + 点开 App 后一直卡在启动页面

### ISSUE THREAD

**Issue by scratlzj** [OpenMindClub/OMC.App#73]
- **系统版本**：IOS 10.0.2
   - **机型**：iPhone6s（最近购买的二手机器）
   - **使用环境**：清空所有后台应用，重启后仍然会卡住
   - **触发情景详细描述**：
   - 点开后卡在启动界面。
   - [手机版本](https://www.dropbox.com/s/al8f0bcc1ul9z65/IMG_1812.PNG?dl=0)
   - [卡在这里](https://www.dropbox.com/s/vcxnuc9840k6cxw/IMG_1806.PNG?dl=0)

**Comment by scratlzj** [comment]
偶尔能成功进入，不知道是不是我手机的问题。

**Comment by xuanmingzhang** [comment]
@scratlzj 请对手机作如下排查：

- 1. 确认是否更新最新版的 app 。app 已在 AppStore 发布最新版，搜索「开智学堂」即可下载更新
- 2. 是否关闭了「使用无线局域网与蜂窝移动的应用」权限，请从 **设置>蜂窝移动网络>使用无线局域网与蜂窝移动的应用>找到「开智学堂」>勾选「无线局域网与蜂窝移动数据」**。

**Comment by scratlzj** [comment]
@xuanmingzhang 
+ 1. 是 3.0（build 31)
+ 2.没关权限

昨天在外面没有网络信号，所以没有手机离线时无法启动 app？今天在家联 wifi 可以正常启动。应该是这个原因，我没想到要联网授权……那就没问题！麻烦了，谢谢。

**Comment by xuanmingzhang** [comment]
@scratlzj 是的，app联网后就可以进入。
