### ISSUE TITLE
[web版] 请增加 esc 关闭卡片;如果阅读卡片能 J 键( 向下滚动) , K 键(向上滚动) 就更好了; 

### ISSUE THREAD

**Issue by linfeng365** [OpenMindClub/OMC.App#75]
[web版] 请增加 esc 关闭卡片;如果阅读卡片能 J 键( 向下滚动) , K 键(向上滚动) 就更好了;

**Comment by lawrencezhang** [comment]
@linfeng365 谢谢建议！未来一定会继续优化快捷键操作的。

**Comment by linfeng365** [comment]
@lawrencezhang 
我有一个更简单的思路:
* `空格`翻转到背面,继续空格向下浏览; `shift+空格`向上浏览; 符合系统默认操作习惯。
* `esc`翻转回正面; 正面`esc`则关闭卡片。
