### ISSUE TITLE
[macOS/iOS]深度学习ch01显示没有卡片数据

### ISSUE THREAD

**Issue by soniclr** [OpenMindClub/OMC.App#77]
系统版本：例如 iOS10.2、macOS Sierra Version 10.12.3
机型：iPhone7Plus
使用环境：开智APP。 safari浏览器
触发情景详细描述：
1.【iOS APP场景】打开开智APP的卡包-课程-ch1-显示没有卡片数据（无法退出） —— 
2. 【macOS场景】打开浏览器safari-http://www.openmindclub.com- 卡包-课程-ch1-显示没有卡片数据

注：2017-03-06号可以正常打开，目前仅ch1没有数据，其他ch0等均正常

**Comment by yangshaoshun** [comment]
经检查，是服务器端的问题，工程师妹子正在解决中
多谢你的反馈
