### ISSUE TITLE
[iOS]添加"缓存-删除选项"功能的建议 #enhancement

### ISSUE THREAD

**Issue by chuanski** [OpenMindClub/OMC.App#78]
- 系统版本：iOS 10.2.1
- 机型：ipad mini2/ipad pro
- 建议：
类似于喜马拉雅app，如图。方便用户自由选择缓存未观看的视频或者删除已看完的视频。
- 说明：
仔细研究了github添加标签的方法 [1](https://help.github.com/articles/applying-labels-to-issues-and-pull-requests/) [2](http://www.jianshu.com/p/5ba1e7f5ad70)，然而我真的没有添加tags的权限
![FIG](https://chuanski.gitbooks.io/writer004/content/_image/20170323_110630.png)

**Comment by yangshaoshun** [comment]
app 中目前已提供了两种删除缓存的选项：

1. 进入某个课程卡包，切换到「视频」，点击右上角的「查看缓存」按钮，可以看到已经缓存的所有视频；点击右上角的「编辑」按钮，可以自由选择视频并删除，如下图所示：

![](http://obu0kc303.bkt.clouddn.com/buffer.png)

2. 切换到主导航「我」，点击左上角的「设置」按钮，点击「清除所有缓存」按钮，如下图所示：

![](http://obu0kc303.bkt.clouddn.com/1136fb4c-65c8-443a-97ab-8084b560e04b.jpg)

**Comment by chuanski** [comment]
@yangshaoshun 谢谢。这个问题明白了。
我在海外，目前无法正常观看视频，尝试缓存视频一直未成功，提示“下载出错，重新下载...”。
尝试[开智学堂 App 使用指南](https://github.com/OpenMindClub/Share/wiki/HbApp)提供的办法，无效，已经填写了 [开智学堂 App 反馈表单](http://openmindclub.mikecrm.com/JFNd28)，未收到反馈。
