### ISSUE TITLE
[iOS]添加横屏功能 #enhancement

### ISSUE THREAD

**Issue by chuanski** [OpenMindClub/OMC.App#79]
- 系统版本：iOS 10.2.1
- 机型：ipad mini2/ipad pro
- 现象：当ipad这样摆放时，

![ipad](http://isource.com/wp-content/uploads/2012/11/8D502E05-CC9F-48F4-8407-C6C8E2DF41EB.png)

开智app的界面是这样的，

![ipad](https://chuanski.gitbooks.io/writer004/content/_image/942B73A0-5FBE-4046-AE9B-8E361C92B199.JPG)

据观察，只有视频的播放界面里有一个旋转按钮。
- 建议：
希望添加全局横屏功能。
- 说明：
仔细研究了github添加标签的方法 [1](https://help.github.com/articles/applying-labels-to-issues-and-pull-requests/) [2](http://www.jianshu.com/p/5ba1e7f5ad70)，然而我真的没有添加tags的权限

**Comment by yangshaoshun** [comment]
你的建议已收到，我们会在后续版本中考虑

* App 推荐在手机上竖屏使用
* iPad 上推荐使用网页版 www.openmindclub.com
