### ISSUE TITLE
开智学堂 App 反馈表单链接显示404

### ISSUE THREAD

**Issue by clock-z** [OpenMindClub/OMC.App#82]
我的课程卡包或者群组问题已经解决，在这里只是提醒下反馈表单链接失效

> 看不到课程卡包或者群组
>进入 App 后，看不到已购买的课程卡包或者群组，有可能是尚未开通权限，请填写[开智学堂 App 反馈表单](https://openmindclub.mikecrm.com/JFNd28p)，运营人员将在 1 个工作日内为你开通学习权限。  

 [开智学堂 App 反馈表单](https://openmindclub.mikecrm.com/JFNd28p)点击打开后显示404。
![404](https://user-images.githubusercontent.com/37953042/39283473-06d6ae8c-4941-11e8-9afd-552c452e234e.PNG)

**Comment by LexieLee** [comment]
@clock-z 谢谢细心的你指出 Bug！你是在「探索开智新世界」卡包中看到的这个错误链接么？课程组刚刚更新了链接，新的 App 反馈地址是：http://openmind.mikecrm.com/p2DGcY 。如果你在其他地方也看到了失效链接，欢迎在此 issue 下留言或向一休反馈❤️

若问题解决，记得 close 此 issue，形成信息闭环，养成好习惯😁～

**Comment by clock-z** [comment]
@LexieLee 
不好意思没说明问题出处，我是在[开智学堂 APP 常见问题自测处理 #35](https://github.com/OpenMindClub/OMC.App/issues/35) 内容操作类里看到的错误链接，刚去看了下还是没有更新链接。

**Comment by LexieLee** [comment]
@clock-z 谢谢提醒！已修正～😁

**Comment by clock-z** [comment]
😊
