### ISSUE TITLE
从卡片返回卡包，顶部top栏的课程名称消失

### ISSUE THREAD

**Issue by yangshaoshun** [OpenMindClub/OMC.App#9]
问题：

”主页“选择”创作“课程，然后进入某个卡包，查看显示当前进度页面，返回之后，顶部 top 栏的课程名称消失。正常应该显示“认知写作学课程二期”。

例如：进入第一个卡包“启程”，然后点击左上角的 “返回“，回到卡包页面，课程名称消失

截图：

![](http://www.mftp.info/20160101/1457326839x1742950694.jpg)

**Comment by ImCaos** [comment]
多谢~已修复到下一个发布版本~

**Comment by badboy315** [comment]
此问题已修复
